### ISSUE TITLE
Missing data in Grafana demo

### ISSUE THREAD

**Issue by mathieugagne** [funbox/sidekiq-influxdb#9]
Hi!

Thanks for the great middleware. It's gonna be really useful.

I took the demo JSON and put up a dashboard on Grafana. I changed the `datasource` to my own.
Sadly the top 4 panels don't have any data. They refer to a series `sidekiq_stats` and other metrics I don't see anywhere in the code.

Here's my config:

```ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add(Sidekiq::Middleware::Server::InfluxDB, influxdb_client: InfluxDB::Rails.client,
                                                     series_name: "sidekiq_jobs",
                                                     tags: {
                                                       application: InfluxDB::Rails.configuration.application_name,
                                                       env:         Rails.env,
                                                     })
  end
end
```

Am i missing a configuration?

Thanks,
Mathieu

**Comment by vassilevsky** [comment]
The dashboard was kindly contributed by @tuwilof

@tuwilof do you know why this might be?

**Comment by tuwilof** [comment]
oops, yep, I forgot the top 4 panels collected by different code
you can remove them
maybe I'll add some more code examples to collect later

**Comment by mathieugagne** [comment]
@tuwilof Thanks again for sharing your Grafana dashboard. Much appreciated!

What if I really like your top 4 panels and I'd like the same too 😄 Any chance you could share how you collect `sidekiq_stats`?
I don't mind if it's opinionated and we wouldn't want to merge in this gem. But having the event type and other stats you exposed could be useful to my org.

**Comment by vassilevsky** [comment]
We really need to add queue and other metrics collection to this library. We'll eventually do that. No ETA right now though.

**Comment by vassilevsky** [comment]
@StoneGod kindly ported the code for the top panels to this library. I have released it in version 1.4.0. Please upgrade the gem. See how to run the new metrics gathering code in the README. Do you have Clockwork in your app? Please let us know how it goes in either case :)

**Comment by mathieugagne** [comment]
Brilliant! I'll be testing this shortly. Greatly appreciated :)

**Comment by mathieugagne** [comment]
Works really well! Much appreciated.

I used `sidekiq-scheduler` instead of `clockwork` since it was already in my stack and fulfills pretty much the same need here. I can share my config if you'd like.

Thanks everyone.

**Comment by vassilevsky** [comment]
Good to hear. Thanks for the feedback.

We don't use Sidekiq Scheduler, but it might be useful for others. You can post your configuration here, or even send a pull request where you add it to the README.
